//  var element;

// element = document.getElementById("h1")
// console.log(element)

// var element2;

// element2 = document.getElementsByClassName("h2")
//  console.log(element2[0])


// var tag;

// tag = document.getElementsByTagName("p")
// console.log(tag[0])


// Action listnear

The addEventListener() method is used to attach an event handler to a particular element.It does not override the existing event handlers.Events are said to be an essential part of the JavaScript.A web page responds according to the event that occurred.Events can be user - generated or generated by API's. An event listener is a JavaScript's procedure that waits for the occurrence of an event.

Onclick
The onchange event occurs when the value of an HTML element is changed

Onclick

Call a function when a button is clicked:



// inharitance
Inheritance enables you to define a class that takes all the functionality from a parent class and allows you to add more.

Using class inheritance, a class can inherit all the methods and properties of another class.

Inheritance is a useful feature that allows code reusability.

To use class inheritance, you use the extends keyword. For example,


// prototype

In JavaScript, a prototype is an object that is associated with every function and contains properties and methods that are shared by all instances of that function. It allows you to add new properties or methods to existing objects or define default values.

// closure

Closure in JavaScript is a form of lexical scoping used to preserve variables from the outer scope of a function in the inner scope of a function. Lexical scoping is the process used to define the scope of a variable by its position in the source code

// Module
In JavaScript, a module is a self-contained unit of code that encapsulates related variables, functions, and classes. It allows you to organize and structure your code into reusable components. Modules help in managing the complexity of large-scale applications by providing a way to split code into smaller, manageable pieces.


// Pattern
A pattern is a series or a sequence that repeats itself. Patterns in JavaScript are essential to practice as they give us a better understanding of loops and nested loops.

Programmers who practice patterns in JavaScript tend to think of the flow of the program faster than other programmers who do not.


// What are the activities that we can perform using DOM

JavaScript can change all the HTML elements in the page
JavaScript can change all the HTML attributes in the page
JavaScript can change all the CSS styles in the page
JavaScript can remove existing HTML elements and attributes
JavaScript can add new HTML elements and attributes
JavaScript can react to all existing HTML events in the page
JavaScript can create new HTML events in the page

//  What are the event-listners in DOM?

The addEventListener() method attaches an event handler to the specified element.

The addEventListener() method attaches an event handler to an element without overwriting existing event handlers.

You can add many event handlers to one element.

You can add many event handlers of the same type to one element, i.e two "click" events.

You can add event listeners to any DOM object not only HTML elements. i.e the window object.

The addEventListener() method makes it easier to control how the event reacts to bubbling.

When using the addEventListener() method, the JavaScript is separated from the HTML markup, for better readability and allows you to add event listeners even when you do not control the HTML markup.

You can easily remove an event listener by using the removeEventListener() method.